name = "photo-blog"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Assets configuration for static files
[assets]
directory = "public"
binding = "ASSETS"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "photo-blog-db"
database_id = "90eee224-f10d-4539-a958-dab293f2d4b6"

# R2 Storage
[[r2_buckets]]
binding = "R2"
bucket_name = "photo-bucket"

[vars]
ENVIRONMENT = "production"
API_URL = "/api"
